name = "portfolio-final"
main = "functions/[[path]].js"
compatibility_date = "2024-01-01"

# This is where Remix builds to
pages_build_output_dir = "./build/client"

kv_namespaces = [
  { id = "MY_KV", binding = "MY_KV" }
]
